project:
  type: website
  output-dir: docs/
website:
  google-analytics: 
    tracking-id: "G-JMLSN1NXWD"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Work in progress, initial prototype"
    type: info
    position: below-navbar  
  title: "Tandem Fluorophores"
  navbar:
    logo: images/hex.svg
    left:
    - text: "Home"
      href: index.qmd
    right:
    - text: "How to Help"
      href: help.qmd
    - icon: github
      href: https://github.com/stepupcytometry/TandemFluorophores
      aria-label: GitHub
  page-footer:
    background: light
    left: Cytometry Discord Group Project
    right: Built with [Quarto](https://quarto.org/).

format:
  html:
    theme: styles.scss